#############################################
#	Grupo Watson							#
#											#
#	GALASSO, Agustina						#
#	LORENZ VIETA, Germán					#
#	MANSILLA, Rodrigo						#
#	OÑA, Diego								#
#############################################

define

#Reglas

#R1 - Resultado de muestra es contaminado
	R1_es_suelo_contaminado sub rule
	when
	{
		$unaMuestra isa suelo 
			has nivel_ph 				$nivel_ph 
			has conductividad_electrica $conductividad_electrica;
		$nivel_ph val < 6.5;
		$conductividad_electrica val > 4;
	}
	then
	{
		(	
			muestra:$unaMuestra
		)	isa es_suelo_contaminado;
	};

#R2 - Resultado de muestra es no contaminado
	R2_es_suelo_no_contaminado sub rule
	when
	{
		$unaMuestra isa suelo 
			has nivel_ph 				$nivel_ph 
			has conductividad_electrica $conductividad_electrica;
		$nivel_ph val >= 6.5;
		$conductividad_electrica val <= 4;
	}
	then
	{
		(	
			muestra:$unaMuestra
		)	isa es_suelo_no_contaminado;
	};


#R3 - Resultado de cultivo es compatible
	R3_es_cultivo_apto sub rule
	when
	{
		$unaMuestra isa suelo 
			has nivel_ph $nivel_ph;
		$unCultivo isa cultivo 
			has ph_min $ph_min 
			has ph_max $ph_max;
		$nivel_ph val >= $ph_min;
		$nivel_ph val <= $ph_max;	

	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa es_cultivo_apto;
	};

#R4 - Resultado de cultivo es no compatible
	R4_es_cultivo_no_apto sub rule
	when
	{
		$unaMuestra isa suelo 
			has nivel_ph $nivel_ph;
		$unCultivo isa cultivo 
			has ph_min $ph_min 
			has ph_max $ph_max;
		$nivel_ph val < $ph_min;
		$nivel_ph val > $ph_max;	

	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa es_cultivo_no_apto;
	};

#R5 - Resultado de fosforo agregar
	R5_fosforo_agregar_muestra sub rule
	when
	{
		$unaMuestra isa suelo 
			has fosforo_suelo $fosforo_suelo;
		$unCultivo isa cultivo 
			has fosforo_cultivo $fosforo_cultivo;
		$fosforo_cultivo val > $fosforo_suelo;
	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa fosforo_agregar_muestra;
	};


#R6 - Resultado de fosforo no agregar
	R6_fosforo_suficiente_muestra sub rule
	when
	{
		$unaMuestra isa suelo 
			has fosforo_suelo $fosforo_suelo;
		$unCultivo isa cultivo 
			has fosforo_cultivo $fosforo_cultivo;
		$fosforo_cultivo val <= $fosforo_suelo;
	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa fosforo_suficiente_muestra;
	};


#R7 - Resultado de nitrogeno agregar
	R7_nitrogeno_agregar_muestra sub rule
	when
	{
		$unaMuestra isa suelo 
			has nitrogeno_suelo $nitrogeno_suelo;
		$unCultivo isa cultivo 
			has nitrogeno_cultivo $nitrogeno_cultivo;
		$nitrogeno_cultivo val > $nitrogeno_suelo;
	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa nitrogeno_agregar_muestra;
	};

#R8 - Resultado de nitrogeno no agregar
	R8_nitrogeno_suficiente_muestra sub rule
	when
	{
		$unaMuestra isa suelo 
			has nitrogeno_suelo $nitrogeno_suelo;
		$unCultivo isa cultivo 
			has nitrogeno_cultivo $nitrogeno_cultivo;
		$nitrogeno_cultivo val <= $nitrogeno_suelo;
	}
	then
	{
		(	
			plantacion:$unCultivo,
			muestra:$unaMuestra
		)	isa nitrogeno_suficiente_muestra;
	};

#R9 - Resultado de potasio arenoso agregar
#R10 - Resultado de potasio franco agregar
#R11 - Resultado de potasio arcilloso agregar


